services:
  postgres:
    image: postgres:15-alpine
    container_name: freebox-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: freebox
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d freebox']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
